name: helm-deploy-action
description: deploy your helm chart to k8s
author: romnn
branding:
  icon: upload-cloud
  color: gray-dark
inputs:
  command:
    description: helm command to be performed (upgrade, install, remove)
    required: true
  # all
  timeout:
    description: timeout for the helm command, e.g. 5m0s
    required: false
  # remove and upgrade
  release:
    description: helm release name
    required: true
  namespace:
    description: k8s namespace
    required: false
    default: default
  kubeconfig-path:
    description: path to kubeconfig file
    required: false
  kubeconfig-inline:
    description: inline kubeconfig
    required: false
  # upgrade
  values:
    description: helm chart values as YAML or JSON
    required: false
  dry-run:
    description: run helm in dry-run mode without an actual deployment
    required: false
    default: false
  atomic:
    description:
      if true, an upgrade process rolls back changes made in case of failed
      upgrade
    required: false
    default: true
  github-token:
    description:
      github API token to fire the deployment_status for github deployments
    required: false
  value-files:
    description:
      additional value files to apply to the helm chart as JSON encoded array or
      string
    required: false
  secrets:
    description:
      secret variables to include in value file interpolation as JSON encoded
      map
    required: false
  # upgrade and push
  chart:
    description: helm chart path
    required: false
  chart-version:
    description: version of the chart
    required: false
  repo:
    description: helm repo url where the chart is stored
    required: false
  repo-alias:
    description: helm repo alias name to use
    required: false
  repo-username:
    description: helm repo username
    required: false
  repo-password:
    description: helm repo password
    required: false
  use-oci:
    description: use OCI protocol when pushing charts
    required: false
    default: true
  dependencies:
    description: helm chart dependencies as YAML or JSON
    required: false
  # push
  app-version:
    description: version of the app
    required: false
  force:
    description: force overrides charts with the same version
    required: false
    default: false
runs:
  using: docker
  image: docker://romnn/helm-deploy-action:latest
