name: helm-deploy-action
description: deploy your helm chart to k8s
author: romnnn
branding:
  icon: upload-cloud
  color: gray-dark
inputs:
  release:
    description: helm release name
    required: true
  chart:
    description: helm chart path
    # when using the remove command, the chart input is not required
    required: false
  version:
    description: Version of the chart
    required: false
  namespace:
    description: k8s namespace
    required: false
    default: default
  repo:
    description: helm repo url where the chart is stored
    required: false
  repo-alias:
    description: helm repo alias name to use 
    required: false
  repo-username:
    description: helm repo username
    required: false
  repo-password:
    description: helm repo password
    required: false
  values:
    description: helm chart values as YAML or JSON
    required: false
  command:
    description: helm command to be performed (upgrade, install, remove)
    required: false
    default: upgrade
  dry-run:
    description: run helm in dry-run mode without an actual deployment
    required: false
    default: false
  timeout:
    description: timeout for the helm command, e.g. 5m0s
    required: false
    default: "5m0s"
  atomic:
    description: if true, an upgrade process rolls back changes made in case of failed upgrade
    required: false
    default: true
  github-token:
    description: github API token to fire the deployment_status for github deployments
    required: false
  value-files:
    description: additional value files to apply to the helm chart as JSON encoded array or string
    required: false
  secrets:
    description: secret variables to include in value file interpolation as JSON encoded map
    required: false
runs:
  using: docker
  image: Dockerfile
