name: test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all

  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build docker container
        run: docker build -t action .

      - name: test helm version
        run: docker run --rm -i --entrypoint=helm action version -c

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: "v1.16.0"
          kubernetes version: "v1.19.2"
      - uses: ./
        with:
          milliseconds: 1000
