name: test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all

  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build docker container
        run: docker build -t action .

      - name: test helm version
        run: docker run --rm -i --entrypoint=helm action version -c

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: "v1.16.0"
          kubernetes version: "v1.19.2"
      - name: Deploy drone
        uses: ./
        with:
          release: drone-release
          chart: stable/drone
          repo: 'https://charts.helm.sh/stable'
          repo-alias: stable
      - name: Deploy couchdb
        uses: ./
        with:
          release: drone-release
          chart: stable/drone
          repo: 'https://charts.helm.sh/stable'
          repo-alias: 'stable'
      - name: Create default2 namespace
        run: kubectl create namespace default2
      - name: Deploy envoy
        uses: ./
        with:
          release: envoy-release
          chart: stable/envoy
          repo: 'https://charts.helm.sh/stable'
          repo-alias: stable
          namespace: default2
      - name: Remove drone deployment
        uses: ./
        with:
          command: remove
          release: drone-release
      - name: Remove envoy deployment
        uses: ./
        with:
          command: remove
          release: envoy-release
          namespace: default2
